#!/system/bin/sh
#=======================================#
#VARIABLES===============================#
BB=/data/adb/magisk/busybox
CLOG=/data/media/0/YourBLchanges.log
BRANCH="Extremely-Aggressive-Profile"
#=======================================#
#=======================================#

am start -a android.intent.action.MAIN -e toasttext "Enabling ExtremeAggressive. This can take few minutes" -n mkadp.toast/.MainActivity

$BB cp -rf /data/adb/modules/butterlimitsforop7poos11uni/system/etc/mkadp/ea/module.prop /data/adb/modules/butterlimitsforop7poos11uni

kmsg3() {
	echo -e "[*] $@" >> $CLOG
}


#=======================================#
#VARIABLES==============================#
NEWLOG2=/data/media/0/.mkadp.log
LOGFU=/data/media/0/butterlimits.log
#=======================================#
LOGBL1=/data/media/0/.mkadp.log
LOGBL2=/data/media/0/butterlimits.log
LOG2=/data/data/com.mkadp.blapp/files/butterlimits.log
LOG2A=/data/data/com.mkadp.blapp/files/zbutterlimits.log
LOG2B=/data/data/com.mkadp.blapp/files/zzbutterlimits.log
IDPATH=/data/adb/modules/butterlimitsforop7poos11uni
MKADPP=$IDPATH/system/etc/mkadp/P
pme='pm enable'
pmd='pm disable'
#=======================================#
#=======================================#

am start -a android.intent.action.MAIN -e toasttext "Removing old Logs" -n mkadp.toast/.MainActivity

rm $NEWLOG2
rm $LOGFU
rm -rf $LOGBL1
rm -rf $LOGBL2
rm -rf $LOG2
rm -rf $LOG2A
rm -rf $LOG2B

am start -a android.intent.action.MAIN -e toasttext "Prepring for heavy works" -n mkadp.toast/.MainActivity

kmsg() {
	echo -e "[*] $@" >> $LOG2B
}

kmsg2() {
	echo -e "[*] $@" >> $LOG2
}

# Safely write value to file
_ctl() {
	# Bail out if file does not exist
	[[ ! -f "$1" ]] && return 1
	
	chmod +w "$1" 2> /dev/null

	# Fetch the current key value
	local curval=`cat "$1" 2> /dev/null`

	# Bail out if value is already set
	[[ "$curval" == "$2" ]] && return 0

	# Write the new value
	echo "$2" > "$1" 2> /dev/null

	# Bail out if ctl fails
	if [[ $? -ne 0 ]]
	then
		err "Failed to ctl $2 to $1.Skipping."
		return 1
	fi

	kmsg "$1: $curval => $2"
}

# Background fork ctl function
ctl() {
	_ctl $@
}

sync

# Print device information prior to execution
kmsg2 $(date)
kmsg2 "ButterLimits"
kmsg2 "Extremely Aggressive"
kmsg2 "SeverBased v10.2.1"
kmsg2 "Last Updated on 30-Dec-2021 18:55 [HH:MM] IST"
kmsg2 "----"
kmsg2 "Prop Tweaks already applied"
kmsg2 "while boot"
kmsg2 "----"
kmsg2 "Database Optimization already done"
kmsg2 "while boot"
kmsg2 "----"
kmsg2 "Already Zipaligned APKs"
kmsg2 "while boot"
kmsg2 "----"
kmsg2 "Already Optimized system"
kmsg2 "while boot"
kmsg2 "----"
kmsg2 $(date) 
kmsg2 "Starting other tweaks works"
kmsg2 "----"


kmsg2 "Killing one idle server to save battery"
kmsg2 "----"

am start -a android.intent.action.MAIN -e toasttext "Killing only one idle server" -n mkadp.toast/.MainActivity

# Killall to save battery
$pme 'com.android.providers.media/com.android.providers.media.MediaScannerReceiver'   | tee -a $LOG2A
killall -9 com.google.android.gms

kmsg $(date) 
kmsg "Killing one server done"
kmsg "----"

# GMS Doze

cmd appops set com.google.android.gms BOOT_COMPLETED allow
cmd appops set com.google.android.ims BOOT_COMPLETED allow
cmd appops set com.google.android.gsf WAKE_LOCK allow
cmd appops set com.google.android.gms AUTO_START allow
cmd appops set com.google.android.ims AUTO_START allow
cmd appops set com.google.android.ims WAKE_LOCK allow

$pme 'com.google.android.gms/com.google.android.gms.mdm.receivers.MdmDeviceAdminReceiver'   | tee -a $LOG2A
$pme 'com.google.android.gms/com.google.android.gms.auth.managed.admin.DeviceAdminReceiver'   | tee -a $LOG2A
$pme 'com.google.android.gms/com.google.android.gms.auth.setup.devicesignals.LockScreenService'   | tee -a $LOG2A
$pme 'com.google.android.gms/com.google.android.gms.mdm.receivers.MdmDeviceAdminReceiver'   | tee -a $LOG2A

# Some stuffs to be enabled

am start -a android.intent.action.MAIN -e toasttext "Enabling some services that were disabled by other Profiles" -n mkadp.toast/.MainActivity

kmsg2 "Enables stuffs that are"
kmsg2 "disabled by other mods if any..."
kmsg2 "----"

$pme --user 0 'com.google.android.gms/.phenotype.service.sync.PhenotypeConfigurator' | tee -a $LOG2A
$pme 'com.google.android.gms/.common.config.PhenotypeCheckinService' | tee -a $LOG2A
#GMS Blocker
$pme 'com.google.android.location.internal.UPLOAD_ANALYTICS' | tee -a $LOG2A
$pme 'com.google.android.apps.wellbeing/.powerstate.impl.PowerStateJobService' | tee -a $LOG2A
$pme 'com.google.android.apps.wellbeing/androidx.work.impl.background.systemjob.SystemJobService' | tee -a $LOG2A
$pme 'com.facebook.katana/com.facebook.analytics.appstatelogger.AppStateIntentService' | tee -a $LOG2A
$pme 'com.facebook.orca/com.facebook.analytics.apptatelogger.AppStateIntentService' | tee -a $LOG2A
$pme 'com.facebook.orca/com.facebook.analytics2.Logger.LollipopUploadService' | tee -a $LOG2A
$pme 'com.google.android.gms/com.google.android.gms.nearby.bootstrap.service.NearbyBootstrapService' | tee -a $LOG2A
$pme 'com.google.android.gms/NearbyMessagesService' | tee -a $LOG2A
$pme 'com.google.android.gms/com.google.android.gms.nearby.connection.service.NearbyConnectionsAndroidService' | tee -a $LOG2A
$pme 'com.google.android.gms/com.google.location.nearby.direct.service.NearbyDirectService' | tee -a $LOG2A
$pme 'com.google.android.gms/com.google.android.gms.lockbox.LockboxService' | tee -a $LOG2A
$pme 'com.google.android.gms/.measurement.PackageMeasurementTaskService' | tee -a $LOG2A
$pme 'com.google.android.gms/com.google.android.gms.auth.trustagent.GoogleTrustAgent' | tee -a $LOG2A

$pme 'com.google.android.gsf/.update.SystemUpdateService'  | tee -a $LOG2A
$pme 'com.android.vending/com.google.android.gms.measurement.AppMeasurementReceiver'  | tee -a $LOG2A
$pme 'com.google.android.gms/.update.SystemUpdateActivity'  | tee -a $LOG2A
$pme 'com.google.android.gms/.update.SystemUpdateService$ActiveReceiver'  | tee -a $LOG2A
$pme 'com.google.android.gms/.update.SystemUpdateService$Receiver'  | tee -a $LOG2A
$pme 'com.google.android.gms/.update.SystemUpdateService$SecretCodeReceiver'  | tee -a $LOG2A
$pme 'com.google.android.gms/com.google.android.gms.analytics.AnalyticsReceiver'  | tee -a $LOG2A
$pme 'com.google.android.gms/com.google.android.gms.measurement.AppMeasurementInstallReferrerReceiver'  | tee -a $LOG2A
$pme 'com.google.android.gms/com.google.android.gms.measurement.AppMeasurementReceiver'  | tee -a $LOG2A
$pme 'com.google.android.gms/com.google.android.gms.measurement.AppMeasurementService'  | tee -a $LOG2A
$pme 'com.google.android.gms/com.google.android.gms.measurement.PackageMeasurementReceiver'  | tee -a $LOG2A
$pme 'com.google.android.gms/com.google.android.gms.measurement.PackageMeasurementService'  | tee -a $LOG2A
$pme 'com.google.android.gms/com.google.android.gms.measurement.service.MeasurementBrokerService'  | tee -a $LOG2A
$pme 'com.google.android.gms/com.google.android.location.internal.AnalyticsSamplerReceiver'  | tee -a $LOG2A
$pme 'com.google.android.gsf/.update.SystemUpdateActivity'  | tee -a $LOG2A
$pme 'com.google.android.gsf/.update.SystemUpdatePanoActivity'  | tee -a $LOG2A
$pme 'com.google.android.gsf/.update.SystemUpdateService$Receiver'  | tee -a $LOG2A
$pme 'com.google.android.gsf/.update.SystemUpdateService$SecretCodeReceiver'  | tee -a $LOG2A

kmsg $(date) 
kmsg "Kernel and CPU Level Tweaks Started"
kmsg "----"

kmsg2 $(date) 
kmsg2 "Kernel and CPU Level Tweaks"
kmsg2 "----"
kmsg2 "Kernel and CPU Level Tweaks"
kmsg2 "----"
kmsg2 "Logs for these will go in"
kmsg2 "hlevel log file with details....."
kmsg2 "----"
kmsg2 "Now applying..."
kmsg2 "----"

am start -a android.intent.action.MAIN -e toasttext "Starting applying of Kerne/CPU/GPU Level Tweaks" -n mkadp.toast/.MainActivity

# Force all CPUs Governor to schedutil
ctl /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor schedutil
ctl /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor schedutil
ctl /sys/devices/system/cpu/cpu2/cpufreq/scaling_governor schedutil
ctl /sys/devices/system/cpu/cpu3/cpufreq/scaling_governor schedutil
ctl /sys/devices/system/cpu/cpu4/cpufreq/scaling_governor schedutil
ctl /sys/devices/system/cpu/cpu5/cpufreq/scaling_governor schedutil
ctl /sys/devices/system/cpu/cpu6/cpufreq/scaling_governor schedutil
ctl /sys/devices/system/cpu/cpu7/cpufreq/scaling_governor schedutil

# Fequency tweaks to all CPUs
ctl /sys/devices/system/cpu/cpu0/cpufreq/schedutil/down_rate_limit_us 75000
ctl /sys/devices/system/cpu/cpu0/cpufreq/schedutil/up_rate_limit_us 0
ctl /sys/devices/system/cpu/cpu0/cpufreq/schedutil/pl 0

ctl /sys/devices/system/cpu/cpu4/cpufreq/schedutil/down_rate_limit_us 75000
ctl /sys/devices/system/cpu/cpu4/cpufreq/schedutil/up_rate_limit_us 0
ctl /sys/devices/system/cpu/cpu4/cpufreq/schedutil/pl 0

ctl /sys/devices/system/cpu/cpu7/cpufreq/schedutil/down_rate_limit_us 75000
ctl /sys/devices/system/cpu/cpu7/cpufreq/schedutil/up_rate_limit_us 0
ctl /sys/devices/system/cpu/cpu7/cpufreq/schedutil/pl 0

ctl /sys/devices/system/cpu/cpu0/online 1
ctl /sys/devices/system/cpu/cpu1/online 1
ctl /sys/devices/system/cpu/cpu2/online 1
ctl /sys/devices/system/cpu/cpu3/online 1
ctl /sys/devices/system/cpu/cpu4/online 1
ctl /sys/devices/system/cpu/cpu5/online 1
ctl /sys/devices/system/cpu/cpu6/online 1
ctl /sys/devices/system/cpu/cpu7/online 1

ctl /sys/devices/system/cpu/cpu0/core_ctl/busy_down_thres 0
ctl /sys/devices/system/cpu/cpu0/core_ctl/busy_up_thres 0

ctl /sys/devices/system/cpu/cpu4/core_ctl/max_cpus 3
ctl /sys/devices/system/cpu/cpu4/core_ctl/min_cpus 2

# Other CPU tweaks
#ctl /dev/cpuctl/cpu.shares 1024


# Force switch off some headache created by kernel logging in case kernel have it enabled;
ctl /proc/sys/debug/exception-trace 0

# Optimized tweaks & enhancements for a improved userspace experience;
ctl /proc/sys/fs/dir-notify-enable 0
ctl /proc/sys/fs/lease-break-time 20

# Entropy tweaks for a slight UI responsivness boost;
ctl /proc/sys/kernel/random/urandom_min_reseed_secs 90

# kernel tweaks to remove wasted CPU cycles kind of headache for kernel
ctl /proc/sys/kernel/panic 0
ctl /proc/sys/kernel/panic_on_oops 0
ctl /proc/sys/kernel/sched_tunable_scaling 0

# disable kernel printk console
ctl /proc/sys/kernel/printk "0 0 0 0"

# Increase how much CPU bandwidth (CPU time) realtime to lightly improved system stability and minimized chance of system freezes & lockups;
ctl /proc/sys/kernel/sched_rt_runtime_us 955000

# Network tweaks to reduced battery consumption when being "actively" connected to a network;
#ctl /proc/sys/net/core/netdev_max_backlog 128
#ctl /proc/sys/net/core/netdev_tstamp_prequeue 0
#ctl /proc/sys/net/ipv4/ipfrag_time 24
#ctl /proc/sys/net/ipv4/tcp_congestion_control westwood
#ctl /proc/sys/net/ipv4/tcp_ecn 1
#ctl /proc/sys/net/ipv4/tcp_fastopen 3
#ctl /proc/sys/net/ipv4/tcp_sack 1
#ctl /proc/sys/net/ipv4/tcp_fack 1
#ctl /proc/sys/net/ipv4/tcp_tw_reuse 1
#ctl /proc/sys/net/ipv4/tcp_dsack 1
#ctl /proc/sys/net/ipv4/tcp_fwmark_accept 0
#ctl /proc/sys/net/ipv4/tcp_keepalive_intvl 320
#ctl /proc/sys/net/ipv4/tcp_keepalive_time 21600
#ctl /proc/sys/net/ipv4/tcp_no_metrics_save 1
#ctl /proc/sys/net/ipv4/tcp_slow_start_after_idle 0
#ctl /proc/sys/net/ipv6/ip6frag_time 48
#
ctl /proc/sys/net/ipv4/tcp_keepalive_probes 5
ctl /proc/sys/net/ipv4/tcp_fin_timeout 30
ctl /proc/sys/net/ipv4/tcp_moderate_rcvbuf 1
ctl /proc/sys/net/ipv4/udp_rmem_min 6144
ctl /proc/sys/net/ipv4/udp_wmem_min 6144
ctl /proc/sys/net/ipv4/tcp_rfc1337 1
ctl /proc/sys/net/ipv4/ip_no_pmtu_disc 0
ctl /proc/sys/net/ipv4/tcp_ecn 0
ctl /proc/sys/net/ipv4/tcp_wmem "6144 87380 2097152"
ctl /proc/sys/net/ipv4/tcp_rmem "6144 87380 2097152"
ctl /proc/sys/net/ipv4/tcp_synack_retries 2
ctl /proc/sys/net/ipv4/tcp_syn_retries 2
ctl /proc/sys/net/ipv4/ip_forward 0
ctl /proc/sys/net/ipv4/tcp_window_scaling 1
ctl /proc/sys/net/ipv4/conf/default/accept_source_route 0
ctl /proc/sys/net/ipv4/conf/all/accept_source_route 0
ctl /proc/sys/net/ipv4/conf/all/accept_redirects 0
ctl /proc/sys/net/ipv4/conf/default/accept_redirects 0
ctl /proc/sys/net/ipv4/conf/all/secure_redirects 0
ctl /proc/sys/net/ipv4/conf/default/secure_redirects 0
ctl /proc/sys/net/ipv4/tcp_tw_recycle 1
ctl /proc/sys/net/ipv4/ip_dynaddr 0
ctl /proc/sys/net/ipv4/tcp_timestamps 0
ctl /proc/sys/net/ipv4/tcp_max_tw_buckets 1440000
ctl /proc/sys/net/ipv4/tcp_mem "57344 57344 524288"
ctl /proc/sys/net/ipv4/tcp_max_tw_buckets 1440000
ctl /proc/sys/net/core/rmem_max 2097152
ctl /proc/sys/net/core/wmem_max 2097152
ctl /proc/sys/net/core/rmem_default 262144
ctl /proc/sys/net/core/wmem_default 262144
ctl /proc/sys/net/core/optmem_max 20480
ctl /proc/sys/net/core/netdev_max_backlog 2500
ctl /proc/sys/net/unix/max_dgram_qlen 50

# VMemory tweaks big improved balance between performance and battery life;
ctl /proc/sys/vm/drop_caches 1
ctl /proc/sys/vm/dirty_background_ratio 11
ctl /proc/sys/vm/dirty_expire_centisecs 400
ctl /proc/sys/vm/page-cluster 0
ctl /proc/sys/vm/dirty_ratio 20
ctl /proc/sys/vm/laptop_mode 0
ctl /proc/sys/vm/block_dump 0
ctl /proc/sys/vm/compact_memory 1
ctl /proc/sys/vm/dirty_writeback_centisecs 3000
ctl /proc/sys/vm/oom_dump_tasks 0
ctl /proc/sys/vm/oom_kill_allocating_task 0
ctl /proc/sys/vm/stat_interval 1103
ctl /proc/sys/vm/panic_on_oom 0
ctl /proc/sys/vm/swappiness 30
ctl /proc/sys/vm/vfs_cache_pressure 94
ctl /proc/sys/vm/overcommit_ratio 50
ctl /proc/sys/vm/extra_free_kbytes 24300
ctl /proc/sys/kernel/random/read_wakeup_threshold 64
ctl /proc/sys/kernel/random/write_wakeup_threshold 2200
ctl /sys/module/lowmemorykiller/parameters/minfree "21816,29088,36360,43632,50904,65448"
ctl /sys/module/lowmemorykiller/parameters/enable_adaptive_lmk 0

ctl /sys/module/lowmemorykiller/parameters/oom_reaper 1

ctl /d/tracing/tracing_on 0
ctl /sys/module/rmnet_data/parameters/rmnet_data_log_level 0

ctl /sys/kernel/debug/kgsl/kgsl-3d0/log_level_cmd 0
ctl /sys/kernel/debug/kgsl/kgsl-3d0/log_level_ctxt 0
ctl /sys/kernel/debug/kgsl/kgsl-3d0/log_level_drv 0
ctl /sys/kernel/debug/kgsl/kgsl-3d0/log_level_mem 0
ctl /sys/kernel/debug/kgsl/kgsl-3d0/log_level_pwr 0

# Turn off a few kernel debuggers for slight boost in both performance and battery life;
ctl /sys/module/bluetooth/parameters/disable_ertm Y
ctl /sys/module/bluetooth/parameters/disable_esco Y
ctl /sys/module/dwc3/parameters/ep_addr_rxdbg_mask 0
ctl /sys/module/dwc3/parameters/ep_addr_txdbg_mask 0
ctl /sys/module/dwc3_msm/parameters/disable_host_mode 0
ctl /sys/module/hid_apple/parameters/fnmode 0
ctl /sys/module/hid/parameters/ignore_special_drivers 0
ctl /sys/module/hid_magicmouse/parameters/emulate_3button N
ctl /sys/module/hid_magicmouse/parameters/emulate_scroll_wheeL N
ctl /sys/module/hid_magicmouse/parameters/scroll_speed 0
ctl /sys/module/mdss_fb/parameters/backlight_dimmer Y
ctl /sys/module/workqueue/parameters/power_efficient Y
ctl /sys/module/sync/parameters/fsync_enabled N
ctl /sys/module/binder/parameters/debug_mask 0
ctl /sys/module/debug/parameters/enable_event_log 0
ctl /sys/module/glink/parameters/debug_mask 0
ctl /sys/module/ip6_tunnel/parameters/log_ecn_error N
ctl /sys/module/subsystem_restart/parameters/enable_ramdumps 0
ctl /sys/module/lowmemorykiller/parameters/debug_level 0
ctl /sys/module/logger/parameters/log_mode 2
ctl /sys/module/msm_show_resume_irq/parameters/debug_mask 0
ctl /sys/module/msm_smd_pkt/parameters/debug_mask 0
ctl /sys/module/sit/parameters/log_ecn_error N
ctl /sys/module/smp2p/parameters/debug_mask 0
ctl /sys/module/usb_bam/parameters/enable_event_log 0
ctl /sys/module/printk/parameters/console_suspend Y
ctl /sys/module/printk/parameters/cpu N
ctl /sys/module/printk/parameters/ignore_loglevel N
ctl /sys/module/printk/parameters/pid N
ctl /sys/module/printk/parameters/time N
ctl /sys/module/service_locator/parameters/enable 0
ctl /sys/module/subsystem_restart/parameters/disable_restart_work 1


for i in $(find /sys/ -name debug_mask); do
ctl $i 0
done
for i in $(find /sys/ -name debug_level); do
ctl $i 0
done
for i in $(find /sys/ -name edac_mc_log_ce); do
ctl $i 0
done
for i in $(find /sys/ -name edac_mc_log_ue); do
ctl $i 0
done
for i in $(find /sys/ -name enable_event_log); do
ctl $i 0
done
for i in $(find /sys/ -name log_ecn_error); do
ctl $i 0
done
for i in $(find /sys/ -name snapshot_crashdumper); do
ctl $i 0
done

# Some Misc
for i in /sys/devices/virtual/block/*/queue/iosched; do
  ctl $i/group_idle 1
done

for i in /sys/devices/virtual/block/*/queue/iosched; do
 ctl $i/low_latency 0
done

for g in /sys/block/*/queue;
do
ctl "${g}"/add_random 0
ctl "${g}"/iostats 0
ctl "${g}"/nomerges 2
ctl "${g}"/rotational 0
ctl "${g}"/rq_affinity 2
ctl "${g}"/iosched/slice_idle 0
ctl "${g}"/iosched/low_latency 0
ctl "${g}"/scheduler cfq
ctl "${g}"/read_ahead_kb 256
ctl "${g}"/nr_requests 8192
done

#am start -a android.intent.action.MAIN -e toasttext "Applying Mount-Related Tweaks..." -n mkadp.toast/.MainActivity
# Remount all partitions with noatime
#for mkk in $($BB mount | grep relatime | cut -d " " -f3);
#do
#$BB mount -o remount,noatime $mkk;
#done

am start -a android.intent.action.MAIN -e toasttext "Still Applying-01...Please Wait" -n mkadp.toast/.MainActivity

for iosched in /sys/block/*/queue/iosched
do
    ctl "$iosched"/slide_idle 0
    ctl "$iosched"/group_idle 1
done

am start -a android.intent.action.MAIN -e toasttext "Still Applying...Please Wait" -n mkadp.toast/.MainActivity

# Dev Stune Boost
# Fast Sensivity in Game
ctl /dev/stune/background/schedtune.boost 15
ctl /dev/stune/foreground/schedtune.boost 15
ctl /dev/stune/rt/schedtune.boost 1
ctl /dev/stune/top-app/schedtune.boost 25
ctl /dev/stune/schedtune.boost 100
ctl /dev/stune/nnapi-hal/schedtune.boost 1
ctl /dev/stune/nnapi-hal/schedtune.prefer_idle 0
ctl /dev/stune/top-app/schedtune.prefer_idle 0
ctl /dev/stune/background/schedtune.prefer_idle 0
ctl /dev/stune/foreground/schedtune.prefer_idle 0
ctl /dev/stune/rt/schedtune.prefer_idle 0
ctl /dev/stune/schedtune.prefer_idle 0

# Fs
ctl /proc/sys/fs/lease-break-time 5
ctl /proc/sys/kernel/perf_cpu_time_max_percent 15
ctl /proc/sys/kernel/sched_min_task_util_for_colocation 0
ctl /proc/sys/kernel/sched_min_task_util_for_boost 0
ctl /proc/sys/kernel/sched_child_runs_first 0
ctl /proc/sys/kernel/sched_boost_top_app 1
ctl /proc/sys/kernel/sched_walt_rotate_big_tasks 1
ctl /proc/sys/kernel/sched_boost 1

# Boost Control Tweak
# Credits to @Ratoriku
ctl /sys/module/boost_control/parameters/app_launch_boost_ms 3000

# GPU frequency based throttling;
ctl /sys/class/kgsl/kgsl-3d0/throttling 0
ctl /sys/class/kgsl/kgsl-3d0/default_pwrlevel 0
ctl /sys/class/kgsl/kgsl-3d0/bus_split 0

#1028 readahead KB
ctl /sys/block/sde/queue/read_ahead_kb 128
ctl /sys/block/sdf/queue/read_ahead_kb 128

# For Idle battery Life
ctl /sys/class/misc/boeffla_wakelock_blocker/wakelock_blocker "qcom_rx_wakelock;wlan;wlan_wow_wl;wlan_extscan_wl;netmgr_wl;NETLINK;IPA_WS;[timerfd];wlan_ipa;wlan_pno_wl;wcnss_filter_lock;IPCRTR_lpass_rx;hal_bluetooth_lock"

# For Net Speed
for i in $(find /sys/class/net -type l); do
  ctl $i/tx_queue_len 128
done
ctl /sys/module/tcp_cubic/parameters/hystart_detect 2

# Misc Kernel Teaks
ctl /sys/kernel/debug/sched_features NEXT_BUDDY
ctl /sys/kernel/debug/sched_features GENTLE_FAIR_SLEEPERS
ctl /sys/kernel/debug/sched_features TTWU_QUEUE
ctl /sys/kernel/debug/sched_features RT_RUNTIME_SHARE
ctl /sys/kernel/debug/sched_features AFFINE_WAKEUPS

for cpu in /sys/devices/system/cpu/*/sched_load_boost
do
    ctl "$cpu" 1
done

for boost in /sys/devices/system/*/cpu_boost
do
    ctl "$boost"/sched_boost_on_input 1
    ctl "$boost"/sched_boost_on_powerkey_input 1
    ctl "$boost"/input_boost_ms 2000
    ctl "$boost"/powerkey_input_boost_ms 500
done

am start -a android.intent.action.MAIN -e toasttext "Still Applying-02...Please Wait" -n mkadp.toast/.MainActivity

chmod -h 644 /sys/module/lowmemorykiller/parameters/cost
ctl /sys/module/lowmemorykiller/parameters/cost 16
chmod -h 644 /sys/module/lowmemorykiller/parameters/adj
ctl /sys/module/lowmemorykiller/parameters/adj "0,1,2,4,7,15"

ctl /sys/power/pm_freeze_timeout 25000

# DS

for i in `ls /sys/class/scsi_disk/`; do
  cat /sys/class/scsi_disk/$i/write_protect 2>/dev/null | grep 1 >/dev/null
  if [ $? -eq 0 ]; then
    ctl /sys/class/scsi_disk/$i/cache_type 'temporary none'
  fi
done

# Disabling Debug ( Reduces the Power Usage )
# All Credits to @Bug_Founder_S10_S8 ( Nuked Dev )

for debug in /sys/kernel/debug/tracing/events/*/enable
do
    ctl "$debug" 0
done
for tracing in /sys/kernel/tracing/events/*/enable
do
    ctl "$tracing" 0
done

am start -a android.intent.action.MAIN -e toasttext "Still Applying-03...Please Wait" -n mkadp.toast/.MainActivity

ctl /sys/wifi/logtrace 0
ctl /sys/wifi/control_logtrace 0
ctl /sys/wifi/logdump_ecntr_enable 0
ctl /sys/power/pm_debug_messages 0
ctl /sys/kernel/debug/debug_enabled N
ctl /sys/kernel/debug/seclog/seclog_debug N
ctl /sys/kernel/debug/tracing/tracing_on 0
ctl /proc/sys/debug/exception-trace 0
ctl /d/tracing/tracing_on 0
ctl /sys/kernel/debug/sched_debug N
ctl /proc/sys/dev/scsi/logging_level 0
ctl /sys/kernel/tracing/options/trace_printk 0
ctl /sys/module/printk/parameters/console_suspend Y
ctl /sys/module/printk/parameters/ignore_loglevel Y
ctl /sys/module/printk/parameters/time N
ctl /proc/sys/kernel/printk 0 0 0 0
ctl /proc/sys/kernel/printk_devkmsg off

for i in ` find /sys/module -name debug_mask`; do  
	ctl $i 0
done

# Adjust a few display props for improved performance as well as overall reduced stuttering and power consumption;
ctl /sys/kernel/debug/mdss_panel_fb0/intf0/mipi/hw_vsync_mode 0
ctl /sys/kernel/debug/mdss_panel_fb0/intf0/mipi/vsync_enable 0
ctl /sys/kernel/debug/mdss_panel_fb0/intf0/bl_max 175
ctl /sys/kernel/debug/mdss_panel_fb0/intf0/brightness_max 175
ctl /sys/kernel/debug/mdss_panel_fb0/intf0/panel_ack_disabled Y
ctl /sys/kernel/debug/mdss_panel_fb0/intf0/partial_update_enabled 1

# Kernel tweaks for overall improved performance;
ctl /proc/sys/kernel/compat-log 0

# Set this as low as possible for performance;
for i in /sys/block/sd*/queue/iosched; do
  ctl $i/back_seek_penalty 1
done;

# Flexibility started from 102+

ctl /proc/sys/fs/dir-notify-enable 0
ctl /proc/sys/fs/lease-break-time 15
ctl /proc/sys/fs/leases-enable 1
ctl /proc/sys/fs/file-max 2097152
ctl /proc/sys/fs/inotify/max_queued_events 131072
ctl /proc/sys/fs/inotify/max_user_watches 131072
ctl /proc/sys/fs/inotify/max_user_instances 1024

kmsg2 $(date) 
kmsg2 "Applied..."
kmsg2 "----"

am start -a android.intent.action.MAIN -e toasttext "Finally...Kernel/CPU/GPU Tweaks Applied" -n mkadp.toast/.MainActivity

kmsg $(date) 
kmsg "Enabling/Tweaking ZRAM"
kmsg "----"
kmsg2 $(date) 
kmsg2 "Enabling/Tweaking ZRAM"
kmsg2 "----"
#
#swapoff /dev/zram0 > /dev/null 2>&1
#swapoff /dev/block/zram0 > /dev/null 2>&1
#swapoff /dev/block/vnswap0 > /dev/null 2>&1
#ctl /sys/block/zram0/reset 1
#ctl /sys/block/zram0/disksize 0
#ctl /sys/block/vnswap0/reset 1
#ctl /sys/block/vnswap0/disksize 0
#ctl /sys/block/zram0/max_comp_streams $CPUS
#ctl /sys/block/vnswap0/max_comp_streams $CPUS
#ctl /sys/block/zram0/disksize $SIZE
#ctl /sys/block/vnswap0/max_comp_streams $CPUS
mkswap /dev/zram0 > /dev/null 2>&1
mkswap /dev/block/zram0 > /dev/null 2>&1
mkswap /dev/block/vnswap0 > /dev/null 2>&1
swapon /dev/zram0 > /dev/null 2>&1
swapon /dev/block/zram0 > /dev/null 2>&1
swapon /dev/block/vnswap0 > /dev/null 2>&1
#
kmsg $(date) 
kmsg "ZRAM Tweaked"
kmsg "----"
kmsg2 $(date) 
kmsg2 "ZRAM Tweaked"
kmsg2 "----"
#

kmsg2 $(date) 
kmsg2 "All Done."
kmsg2 "Enjoy ButterLimits Extrem Mode"
kmsg2 "----"

# Push a semi-needed log to the internal storage with a "report" if the script could be executed or not;
kmsg $(date) 
kmsg "MKADP HAS EXECUTED TASK SUCCESSFULLY. ENJOY!"

kmsg3 $(date) 
kmsg3 "Extremely Aggressive Mode Enabled"
kmsg3 "----"

$$BB cp -rf /data/media/0/YourBLchanges.log /data/data/com.mkadp.blapp/files/YourBLchanges.log

am start -a android.intent.action.MAIN -e toasttext "Wiping Cache" -n mkadp.toast/.MainActivity

$BB rm -rf /cache/*	

am start -a android.intent.action.MAIN -e toasttext "All Done. Thankyou for your patience" -n mkadp.toast/.MainActivity

FILEBAT=$MKADPP/bat
FILEBAL=$MKADPP/bal
FILEEXT=$MKADPP/ext
FILEEA=$MKADPP/ea
MKADPOENF/data/mkadp/O/enf
MKADPOPER/data/mkadp/O/per

if [ -f "$FILEEXT" ]; then
	rm -rf $FILEEXT
	echo -n >$FILEEA
	am start -n com.mkadp.blapp/.activities.LogsActivity
	exit 0
else
	if [ -f "$FILEEA" ]; then
		am start -n com.mkadp.blapp/.activities.LogsActivity
		exit 0
	else
		if [ -f "$FILEBAT" ]; then
			rm -rf $FILEBAT
			echo -n >$FILEEA
			$busybox mount -o remount,rw /vendor
			$BB cp -rf /vendor/lib/egl/libEGL_adreno.so.bak /vendor/lib/egl/libEGL_adreno.so
			$BB rm -rf /vendor/lib/egl/libEGL_adreno.so.bak
			$BB rm -rf /vendor/lib/egl/egl.cfg
			$busybox mount -o remount,ro /vendor			
			am start -a android.intent.action.MAIN -e toasttext "You were on Battery Profile" -n mkadp.toast/.MainActivity
			sleep 2
			am start -a android.intent.action.MAIN -e toasttext "Reboot needed" -n mkadp.toast/.MainActivity
			sleep 1
			am start -a android.intent.action.MAIN -e toasttext "Device will reboot in 5 secs..." -n mkadp.toast/.MainActivity
			sleep 1
			am start -a android.intent.action.MAIN -e toasttext "Device will reboot in 4 secs..." -n mkadp.toast/.MainActivity
			sleep 1
			am start -a android.intent.action.MAIN -e toasttext "Device will reboot in 3 secs..." -n mkadp.toast/.MainActivity
			sleep 1
			am start -a android.intent.action.MAIN -e toasttext "Device will reboot in 2 secs..." -n mkadp.toast/.MainActivity
			sleep 1
			am start -a android.intent.action.MAIN -e toasttext "Device will reboot in 1 sec..." -n mkadp.toast/.MainActivity
			sleep 1
			am start -a android.intent.action.MAIN -e toasttext "Device is rebooting..." -n mkadp.toast/.MainActivity
			sleep 1
			reboot
		else
			if [ -f "$FILEBAL" ]; then
				rm -rf $FILEBAL
				echo -n >$FILEEA
				$busybox mount -o remount,rw /vendor
				$BB cp -rf /vendor/lib/egl/libEGL_adreno.so.bak /vendor/lib/egl/libEGL_adreno.so
				$BB rm -rf /vendor/lib/egl/libEGL_adreno.so.bak
				$BB rm -rf /vendor/lib/egl/egl.cfg
				$busybox mount -o remount,ro /vendor				
				am start -a android.intent.action.MAIN -e toasttext "You were on Balanced Profile" -n mkadp.toast/.MainActivity
				sleep 2
				am start -a android.intent.action.MAIN -e toasttext "Reboot needed" -n mkadp.toast/.MainActivity
				sleep 1
				am start -a android.intent.action.MAIN -e toasttext "Device will reboot in 5 secs..." -n mkadp.toast/.MainActivity
				sleep 1
				am start -a android.intent.action.MAIN -e toasttext "Device will reboot in 4 secs..." -n mkadp.toast/.MainActivity
				sleep 1
				am start -a android.intent.action.MAIN -e toasttext "Device will reboot in 3 secs..." -n mkadp.toast/.MainActivity
				sleep 1
				am start -a android.intent.action.MAIN -e toasttext "Device will reboot in 2 secs..." -n mkadp.toast/.MainActivity
				sleep 1
				am start -a android.intent.action.MAIN -e toasttext "Device will reboot in 1 sec..." -n mkadp.toast/.MainActivity
				sleep 1
				am start -a android.intent.action.MAIN -e toasttext "Device is rebooting..." -n mkadp.toast/.MainActivity
				sleep 1
				reboot
			else
				echo -n >$FILEEA
				am start -n com.mkadp.blapp/.activities.LogsActivity
			fi
		fi
	fi
fi
